---
prepare:
    tasks:
        - npm i

deployment:
    tasks:
        - export DEPLOYPATH=/home3/r98940lagi/public_html/
        - yarn build

running:
    tasks:
        - /bin/cp -R build $DEPLOYPATH